spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${port}/${dbName}
    password: ${dbUser}
    name: ${dbPass}
    
---

spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://${port}/${dbName}
    password: ${dbUser}
    name: ${dbPass}